package com.example.leavemangmtapp.navigation

const val ROUTE_HOME = "Homepage"
const val ROUTE_LOGIN = "Login"
const val ROUTE_REGISTER = "Register"
const val ROUTE_APPLY = "ApplyLeave"
const val ROUTE_ADMINLOGIN = "AdminLogin"
const val ROUTE_ADMINHOME = "AdminHomepage"
const val ROUTE_LEAVEAALOCATION = "LeaveAllocation"
const val ROUTE_VIEWEMPLOYEES = "ViewEmployees"
const val ROUTE_ADDEMPLOYEE = "AddEmployee"
const val ROUTE_EMPLOYEEPROFILE = "EmployeeProfile"
const val ROUTE_ADMINSETTINGS = "AdminSettings"
const val ROUTE_EMPLOYEESETTINGS = "EmployeeSettings"
const val ROUTE_SPLASHSCREEN = "SplashScreen"